In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import scipy.stats as sts
from scipy.stats import linregress
import numpy as np
import seaborn as sns
import scipy.stats as st

In [2]:
accident_df = pd.read_csv("all.csv", low_memory=False)

accident_df.head()

,Unnamed: 0,Accident_Index,1st_Road_Class,Accident_Severity,Year,Date,Day_of_Week,Latitude,Light_Conditions,Local_Authority_(District),...,Journey_Purpose_of_Driver,Junction_Location,make,model,Propulsion_Code,Sex_of_Driver,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Type,Was_Vehicle_Left_Hand_Drive
0,478587,201001BS70003,B,Slight,2010,2010-01-11,Monday,51.484087,Daylight,Kensington and Chelsea,...,Commuting to/from work,Mid Junction - on roundabout or on main road,CITROEN,BERLINGO FIRST 600,Petrol,Female,No tow/articulation,Turning right,Van / Goods 3.5 tonnes mgw or under,No
1,478588,201001BS70004,A,Slight,2010,2010-01-11,Monday,51.509212,Darkness - lights lit,Kensington and Chelsea,...,Journey as part of work,Mid Junction - on roundabout or on main road,RENAULT,SCENIC DYN DCI 130,Heavy oil,Male,No tow/articulation,Going ahead other,Car,No
2,478589,201001BS70007,Unclassified,Slight,2010,2010-01-02,Saturday,51.513314,Darkness - lights lit,Kensington and Chelsea,...,Other/Not known (2005-10),Mid Junction - on roundabout or on main road,NISSAN,PRIMERA SVE CVT,Petrol,Female,No tow/articulation,Going ahead right-hand bend,Car,No
3,478590,201001BS70007,Unclassified,Slight,2010,2010-01-02,Saturday,51.513314,Darkness - lights lit,Kensington and Chelsea,...,Other/Not known (2005-10),Mid Junction - on roundabout or on main road,MERCEDES,A140 ELEGANCE,Petrol,Female,No tow/articulation,Going ahead other,Car,No
4,478591,201001BS70008,A,Slight,2010,2010-01-04,Monday,51.484361,Darkness - lights lit,Kensington and Chelsea,...,Journey as part of work,Mid Junction - on roundabout or on main road,VAUXHALL,ZAFIRA ELEGANCE DTI,Heavy oil,Male,No tow/articulation,Turning right,Taxi/Private hire car,No

In [29]:
all_average = accident_df.groupby(["Speed_limit"]).mean()
all_average.sort_values(by=["Number_of_Casualties"], ascending=False)
average_casualties = all_average["Number_of_Casualties"]
len(average_casualties)

8

In [24]:
all_average.

,Unnamed: 0,Year,Latitude,Longitude,Number_of_Casualties,Number_of_Vehicles,Age_of_Vehicle,Engine_Capacity_.CC.
Speed_limit,,,,,,,,
10,1.232133e+06,2015.000000,51.616118,-0.133423,1.000000,1.000000,10.000000,1587.000000
15,6.230945e+05,2010.000000,55.785185,-4.011792,1.000000,2.000000,9.500000,1576.000000
20,1.178446e+06,2014.227345,52.507229,-1.435005,1.247302,1.932646,7.689326,1726.999664
30,1.005954e+06,2013.123729,52.486797,-1.306082,1.359357,2.051464,7.559474,1645.143739
40,1.026175e+06,2013.163722,52.433875,-1.320840,1.555149,2.211734,7.530384,1681.721859
50,1.047666e+06,2013.295424,52.441736,-1.341802,1.653223,2.341947,7.436005,1748.595492
60,1.021696e+06,2013.045297,52.831584,-1.635675,1.646950,2.086204,7.724990,1701.688403
70,1.029928e+06,2013.141575,52.466215,-1.286745,1.824399,2.689896,6.937580,1878.523360

In [28]:


corr=round(st.pearsonr(all_average[""],average_casualties)[0],2)
print(f"The correlation is {corr}")

ValueError: x and y must have the same length.

In [18]:
accident_df["Number_of_Casualties"].max()

93